import Footer from "@/components/ui/Footer";
import Navbar from "@/components/ui/Navbar";
import "../styles/globals.css";
import favico from "../../public/favicon.ico"

export const metadata = {
  title: "Rk - Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href={favico.src} type="image/x-icon"/>
      </head>
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
